[build]
  command = "bun run build"
  functions = "functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/scheduler/hyperplanning/:schedulerId/:dateParameter"
  to = "https://hyperplanning.iut.u-bordeaux.fr/Telechargements/ical/Edt.ics?version=2023.0.5.0&icalsecurise=:schedulerId&param=:dateParameter"
  status = 200