[build]
  command = "vue-cli-service build"
  functions = "functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/scheduler/hyperplanning/:schedulerId/:dateParameter"
  to = "https://hyperplanning.iut.u-bordeaux.fr/Telechargements/ical/Edt.ics?version=2021.0.1.3&idICal=:schedulerId&param=:dateParameter"
  status = 200
